name: First_Action

on: [push]

jobs:
  build:
    runs_on: ubuntu:latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run test
        run: |
          cd src
          python -m pytest addition.py
